# Generated by Django 2.1.15 on 2022-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationBox',
            fields=[
                ('sentence', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('valence', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('arousal', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('rank_value', models.DecimalField(decimal_places=2, default=0.4432149479808698, max_digits=4)),
                ('is_annotated', models.BooleanField(default=False)),
                ('is_miscellaneous', models.BooleanField(default=False)),
            ],
        ),
    ]
