# Generated by Django 2.1.15 on 2022-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220512_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationbox',
            name='rank_value',
            field=models.DecimalField(decimal_places=2, default=0.21138489141785055, max_digits=4),
        ),
    ]
