# Generated by Django 2.1.15 on 2022-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220512_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbox',
            name='is_drafted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotationbox',
            name='rank_value',
            field=models.DecimalField(decimal_places=2, default=0.5629033229663243, max_digits=4),
        ),
    ]
