# Generated by Django 2.1.15 on 2022-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220523_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationbox',
            name='rank_value',
            field=models.DecimalField(decimal_places=2, default=0.7396899177391281, max_digits=4),
        ),
        migrations.AlterField(
            model_name='annotationbox',
            name='sentence',
            field=models.CharField(max_length=2000),
        ),
    ]
