# Generated by Django 2.1.15 on 2022-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220524_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbox',
            name='draft_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotationbox',
            name='article_id',
            field=models.IntegerField(null=True),
        ),
    ]
