# Generated by Django 2.1.15 on 2022-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220602_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationbox',
            name='draft_time',
            field=models.DateTimeField(null=True),
        ),
    ]
